server.port=8888
spring.application.name=config-server

spring.cloud.config.server.git.uri=/home/cristo/Documentos/Springboot/paymentchainparent/config-server-repo

spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=master
# spring.cloud.compatibility-verifier.enabled=false
spring.security.user.name=admin
spring.security.user.password=qwerty